// Common
export const API_CALL_ERROR = "API_CALL_ERROR";
export const API_CALL_START = "API_CALL_START";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const CLOSE_ALERT = "CLOSE_ALERT";


// Employees
export const CREATE_EMPLOYEE_LOADING = "CREATE_EMPLOYEE_LOADING";
export const CREATE_EMPLOYEE_ERROR = "CREATE_EMPLOYEE_ERROR";
export const CREATE_EMPLOYEE_COMPLETE = "CREATE_EMPLOYEE_COMPLETE";

export const UPDATE_EMPLOYEE_LOADING= "UPDATE_EMPLOYEE_LOADING";
export const UPDATE_EMPLOYEE_ERROR= "UPDATE_EMPLOYEE_ERROR";
export const UPDATE_EMPLOYEE_COMPLETE= "UPDATE_EMPLOYEE_COMPLETE";

export const SEARCH_EMPLOYEES_LOADING= "SEARCH_EMPLOYEES_LOADING";
export const SEARCH_EMPLOYEES_ERROR= "SEARCH_EMPLOYEES_ERROR";
export const SEARCH_EMPLOYEES_COMPLETE= "SEARCH_EMPLOYEES_COMPLETE";

export const DELETE_EMPLOYEE_LOADING= "DELETE_EMPLOYEE_LOADING";
export const DELETE_EMPLOYEE_ERROR= "DELETE_EMPLOYEE_ERROR";
export const DELETE_EMPLOYEE_COMPLETE= "DELETE_EMPLOYEE_COMPLETE";


//CareLead - Group Management Actions
export const CREATE_GROUP = "CREATE_GROUP";
export const DEACTIVATE_GROUP = "DEACTIVATE_GROUP";
export const ADD_CAREMEMBER_TO_GROUP = "ADD_CAREMEMBER_TO_GROUP";
export const REMOVE_CAREMEMBER_FROM_GROUP = "REMOVE_CAREMEMBER_FROM_GROUP";
export const SEARCH_GROUP = "SEARCH_GROUP";
export const RETRIEVE_GROUPS = "RETRIEVE_GROUPS";
export const UPDATE_GROUP = "UPDATE_GROUP";
