// Common
export const API_CALL_ERROR = "API_CALL_ERROR";
export const API_CALL_START = "API_CALL_START";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";

// Employees
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const RETRIEVE_EMPLOYEES = "RETRIEVE_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";

//CareLead - Group Management Actions
export const CREATE_GROUP = "CREATE_GROUP";
export const DEACTIVATE_GROUP = "DEACTIVATE_GROUP";
export const ADD_CAREMEMBER_TO_GROUP = "ADD_CAREMEMBER_TO_GROUP";
export const REMOVE_CAREMEMBER_FROM_GROUP = "REMOVE_CAREMEMBER_FROM_GROUP";
export const SEARCH_GROUP = "SEARCH_GROUP";
export const RETRIEVE_GROUPS = "RETRIEVE_GROUPS";
export const UPDATE_GROUP = "UPDATE_GROUP";
