// Common
export const API_CALL_ERROR = "API_CALL_ERROR";
export const API_CALL_START = "API_CALL_START";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const LIST_COUNTRIES_LOADING = "LIST_COUNTRIES_LOADING";
export const LIST_COUNTRIES_ERROR = "LIST_COUNTRIES_ERROR";
export const LIST_COUNTRIES_COMPLETE = "LIST_COUNTRIES_COMPLETE";

export const LIST_BUSINESS_UNITS_LOADING = "LIST_BUSINESS_UNITS_LOADING";
export const LIST_BUSINESS_UNITS_ERROR = "LIST_BUSINESS_UNITS_ERROR";
export const LIST_BUSINESS_UNITS_COMPLETE = "LIST_BUSINESS_UNITS_COMPLETE";

// Employees
export const CREATE_EMPLOYEE_LOADING = "CREATE_EMPLOYEE_LOADING";
export const CREATE_EMPLOYEE_ERROR = "CREATE_EMPLOYEE_ERROR";
export const CREATE_EMPLOYEE_COMPLETE = "CREATE_EMPLOYEE_COMPLETE";

export const UPDATE_EMPLOYEE_LOADING = "UPDATE_EMPLOYEE_LOADING";
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR";
export const UPDATE_EMPLOYEE_COMPLETE = "UPDATE_EMPLOYEE_COMPLETE";

export const SEARCH_EMPLOYEES_LOADING = "SEARCH_EMPLOYEES_LOADING";
export const SEARCH_EMPLOYEES_ERROR = "SEARCH_EMPLOYEES_ERROR";
export const SEARCH_EMPLOYEES_COMPLETE = "SEARCH_EMPLOYEES_COMPLETE";

export const DELETE_EMPLOYEE_LOADING = "DELETE_EMPLOYEE_LOADING";
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR";
export const DELETE_EMPLOYEE_COMPLETE = "DELETE_EMPLOYEE_COMPLETE";

// Groups
export const CREATE_GROUP_LOADING = "CREATE_GROUP_LOADING";
export const CREATE_GROUP_ERROR = "CREATE_GROUP_ERROR";
export const CREATE_GROUP_COMPLETE = "CREATE_GROUP_COMPLETE";

export const UPDATE_GROUP_LOADING = "UPDATE_GROUP_LOADING";
export const UPDATE_GROUP_ERROR = "UPDATE_GROUP_ERROR";
export const UPDATE_GROUP_COMPLETE = "UPDATE_GROUP_COMPLETE";

export const SEARCH_GROUPS_LOADING = "SEARCH_GROUPS_LOADING";
export const SEARCH_GROUPS_ERROR = "SEARCH_GROUPS_ERROR";
export const SEARCH_GROUPS_COMPLETE = "SEARCH_GROUPS_COMPLETE";

export const DELETE_GROUP_LOADING = "DELETE_GROUP_LOADING";
export const DELETE_GROUP_ERROR = "DELETE_GROUP_ERROR";
export const DELETE_GROUP_COMPLETE = "DELETE_GROUP_COMPLETE";

export const DEACTIVATE_GROUP_LOADING = "DEACTIVATE_GROUP";
export const DEACTIVATE_GROUP_ERROR = "DEACTIVATE_GROUP_ERROR";
export const DEACTIVATE_GROUP_COMPLETE = "DEACTIVATE_GROUP_COMPLETE";

export const ADD_CAREMEMBER_TO_GROUP_LOADING =
  "ADD_CAREMEMBER_TO_GROUP_LOADING";
export const ADD_CAREMEMBER_TO_GROUP_ERROR =
  "ADD_CAREMEMBER_TO_GROUP_ERROR";
export const ADD_CAREMEMBER_TO_GROUP_COMPLETE =
  "ADD_CAREMEMBER_TO_GROUP_COMPLETE";

export const REMOVE_CAREMEMBER_FROM_GROUP_LOADING =
  "REMOVE_CAREMEMBER_FROM_GROUP_LOADING";
export const REMOVE_CAREMEMBER_FROM_GROUP_ERROR =
  "REMOVE_CAREMEMBER_FROM_GROUP_ERROR";
export const REMOVE_CAREMEMBER_FROM_GROUP_COMPLETE =
  "REMOVE_CAREMEMBER_FROM_GROUP_COMPLETE";
